### ISSUE TITLE
Doesnt' seem to work

### ISSUE THREAD

**Issue by help137** [Stefan-Code/amazon-sponsored-items-blocker#1]
Doesn't seem to work. Sponsored items still showing on amazon.com

Windows 10 Pro
Firefox 82
Installed via TamperMonkey 4.11

**Comment by Stefan-Code** [comment]
Should be fixed. I did not notice because ublock origin does a decent job at blocking those too nowadays. Can you try again, @help137 ?

**Comment by help137** [comment]
> Should be fixed. I did not notice because ublock origin does a decent job at blocking those too nowadays. Can you try again, @help137 ?

That seems to have done the trick. I'm still getting one "Sponsored" bloack at the top of the page, but the ones it was insertign into the list are gone. 

-K
